version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_penyakit
    environment:
      POSTGRES_DB: penyakit_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/schema_postgres.sql:/docker-entrypoint-initdb.d/schema_postgres.sql
      - ./data:/data
    networks:
      - penyakit_network

  spark-master:
    image: bitnami/spark:3.4
    container_name: spark_master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./data:/data
      - ./src:/app
      - ./scripts:/scripts
    networks:
      - penyakit_network

  spark-worker:
    image: bitnami/spark:3.4
    container_name: spark_worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    depends_on:
      - spark-master
    volumes:
      - ./data:/data
      - ./src:/app
      - ./scripts:/scripts
    networks:
      - penyakit_network

  jupyter:
    image: jupyter/pyspark-notebook:latest
    container_name: jupyter_notebook
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=penyakit123
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/home/jovyan/work/data
      - ./src:/home/jovyan/work/src
    networks:
      - penyakit_network
    depends_on:
      - postgres
      - spark-master

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - penyakit_network
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data:

networks:
  penyakit_network:
    driver: bridge
