version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres_penyakit
    environment:
      POSTGRES_DB: penyakit_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/schema_postgres.sql:/docker-entrypoint-initdb.d/schema_postgres.sql
      - ./data:/data
    networks:
      - penyakit_network

  spark-master:
    image:  bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark_master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./data:/data
      - ./src:/app
      - ./scripts:/scripts
    networks:
      - penyakit_network

  spark-worker:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark_worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    depends_on:
      - spark-master
    volumes:
      - ./data:/data
      - ./src:/app
      - ./scripts:/scripts
    networks:
      - penyakit_network

volumes:
  postgres_data:
networks:
  penyakit_network:
    driver: bridge
